---
title: "20240711_hdp_tree"
format: html
editor: visual
---

```{r}
library(readr)
library(ape)
devtools::load_all()
```

## Load data

```{r}
#tree <- read.tree('/Users/dfridljand/Documents/Research_too_large/2024-Beerenwinkel/data/WholeExome/CRC09_cancer_50nanFilter.cellphy.newick')
```

```{r}
# Print a summary of the tree
#summary(tree)

# Plot the tree
#plot(tree)
```

```{r}
#read csv file '/Users/dfridljand/Documents/Research_too_large/2024-Beerenwinkel/data/WholeExome/vcf_tricl_mut_counts.csv'
#vcf_tricl_mut_counts <- read_csv('/Users/dfridljand/Documents/Research_too_large/2024-Beerenwinkel/data/WholeExome/vcf_tricl_mut_counts.csv')
```

```{r}
cnsignatures_input_filtered_cin_quant <- read_csv("~/Documents/Research_too_large/2024-Beerenwinkel/data/TumorProfilerData/cnsignatures_input_filtered_cin_quant.csv")

cnsignatures_input_filtered_cin_quant[1:5, 1:5]
```

```{r}
# Load necessary libraries
library(dplyr)
library(tidyr)

# Assuming cnsignatures_input_filtered_cin_quant is your dataframe
# Split the 'sample' column into 'sample_tumor' and 'sample_node'
cnsignatures_input_filtered_cin_quant <- cnsignatures_input_filtered_cin_quant %>%
  separate(sample, into = c("sample_tumor", "sample_node"), sep = "_", remove = FALSE) %>%
  mutate(sample_tumor = as.factor(sample_tumor))

cnsignatures_input_filtered_cin_quant_sample_tumor <- cnsignatures_input_filtered_cin_quant$sample_tumor
cnsignatures_input_filtered_cin_quant_sample_node <- cnsignatures_input_filtered_cin_quant$sample_node

#Drop them
cnsignatures_input_filtered_cin_quant <- cnsignatures_input_filtered_cin_quant %>%
  select(-sample_tumor, -sample_node)

# Set row names using the "sample" column
rownames(cnsignatures_input_filtered_cin_quant) <- cnsignatures_input_filtered_cin_quant$sample

# Remove the "sample" column
cnsignatures_input_filtered_cin_quant$sample <- NULL

# Print the updated dataframe
print(cnsignatures_input_filtered_cin_quant)
```

```{r}
sample_tumors_unique <- unique(cnsignatures_input_filtered_cin_quant_sample_tumor)
n_sample_tumors_unique <- length(sample_tumors_unique)

```

```{r}
sample_tumor_int <- as.integer(cnsignatures_input_filtered_cin_quant_sample_tumor)

ppindex <-  c(0, rep(1, n_sample_tumors_unique), sample_tumor_int)
ppindex
```

```{r inithdp}
# initialise HDP
hdp_mut <- hdp_init(ppindex = ppindex, # index of parental nodes
                    cpindex = 1 + ppindex, # index of concentration param
                    hh=rep(1, ncol(cnsignatures_input_filtered_cin_quant)), # prior is uniform over the 96 mutation categories
                    alphaa=rep(1, 1+ max(ppindex)), # shape hyperparams for five different CPs
                    alphab=rep(1, 1+ max(ppindex))) # rate hyperparams for five different CPs


plot_tree(hdp_mut)
```

```{r}
dpindex = (2+n_sample_tumors_unique):numdp(hdp_mut)
cnsignatures_input_filtered_cin_quant <- as.data.frame(cnsignatures_input_filtered_cin_quant)
# add data to leaf nodes (one per cancer sample, in row order of mut_count)
hdp_mut <- hdp_setdata(hdp_mut, 
                       dpindex = dpindex, # index of nodes to add data to
                       data = cnsignatures_input_filtered_cin_quant) # input data (mutation counts, sample rows match up with specified dpindex)
```

```{r}


hdp_mut
```
